### ISSUE TITLE
Perlin noise doesn't work with negative coordinates

### ISSUE THREAD

**Issue by geotre** [Nycto/PerlinNim#5]
Using a slightly modified version of the example:

```nim
import perlin, random, math

randomize()
let noise = newNoise()

for y in 0..10:
    for x in 0..20:
        echo noise.perlin(-x, -y)
```

sample from output:

```
5.716112000000001
3.282981724160003
11.60813961216002
60.05479239680006
205.2020080716802
-4.865088000000002
-7.199699819840007
-23.70134179840006
-83.59753790208008
-238.8913038540804
-3.896455000000001
0.9298921574400039
11.76152181184003
41.58326589440004
119.6164463395202
-8.679456000000002
```

Numbers are not in the range 0-1 as expected from the docs. Swapping `perlin` for `simplex` works as expected

**Comment by Nycto** [comment]
Finally got a chance to take a look at this. Turns out I was doing some unsafe float truncation that didn't work with negative numbers. Should be resolved now.
