### ISSUE TITLE
value out of range error?

### ISSUE THREAD

**Issue by RobertRautenbach** [Nycto/PerlinNim#6]
Hi when compiling on certain systems the randomseed() proc is raising a value out of range error.
I've changed:
```uint32(rand(high(int)))```
to
```uint32(rand(high(int16)))```
It seems to have fixed the issue, but I'm not sure why it was happening in the first place. Are you able to shed any light on this?

**Comment by RobertRautenbach** [comment]
Ah I believe its because int isn't guaranteed to be 32 bits. Explicitly saying int32 fixes it.

**Comment by Nycto** [comment]
Can you submit a PR with the change you need?

**Comment by Nycto** [comment]
Thanks for resolving this, and apologies for the delay. Needed to find some time to confirm the exact cause of the build failures.

I've published version 0.7.0, which includes this fix.
